# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# 基础站点设置
locale: "en-US"
title: "HOME PAGE"
title_separator: "-"
name: &name "Zuojie Li"
description: &description "personal description"
url: "https://zuojie-li.github.io/" # 站点的基础主机名和协议
baseurl: "" # 站点的子路径，例如 "/blog"
repository: "academicpages/academicpages.github.io"

# 站点作者信息
author:
  # 个人信息
  avatar: "picture1.png"
  name: "李作杰"
  pronouns: # 例如："男"
  bio: "山东泰安 射手座"
  location: "北京 中国"
  employer: "北京师范大学"
  uri: # 个人主页URL
  email: "ZuojieLi@yeah.net"

  # 学术网站
  arxiv: # URL
  googlescholar: "https://scholar.google.com/citations?user=_Q6Z4QUAAAAJ"
  impactstory: # URL
  orcid: "http://orcid.org/0009-0001-1131-1635"
  semantic: # URL
  researchgate: # URL
  scopus: # URL

  # 代码仓库和软件开发
  bitbucket: # 用户名
  codepen: # 用户名
  dribbble: # 用户名
  github: # "academicpages"
  kaggle: # 用户名
  stackoverflow: # 用户号或"用户号/用户名"

  # 社交媒体
  facebook: "share/1B9pZ1ZSaN/?mibextid=wwXIfr"
  flickr: # 用户名
  foursquare: # 用户名
  goodreads: # 用户名
  google_plus: # 用户名
  keybase: # 用户名
  instagram: # 用户名
  lastfm: # 用户名
  linkedin: # 用户名
  mastodon: # URL
  medium: # URL
  pinterest: # 用户名
  soundcloud: # 用户名
  steam: # 用户名
  telegram: # URL
  tumblr: # 用户名
  twitter: # X / Twitter 用户名
  vine: # 用户名
  weibo: # 用户名
  wikipedia: # 用户名
  xing: # 用户名
  youtube: # 用户名
  zhihu: # 用户名

# 出版物类别
publication_category:
  books:
    title: 'Patent'
  manuscripts:
    title: 'Journal Articles(Rep.)'
  conferences:
    title: 'Conference Papers'

# 站点设置
teaser: # 预览图文件名，放在 /images/ 目录下
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false
comments:
  provider: # false, "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname:
  discourse:
    server: # 例如：meta.discourse.org
  facebook:
    appid:
    num_posts: # 默认 5
    colorscheme: # "light" (默认), "dark"
staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "gh-pages"
  commitMessage: "New comment."
  filename: comment-{@timestamp}
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601"
atom_feed:
  hide: false
  path: # 默认使用 feed.xml

# SEO 相关
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

# 社交分享
twitter:
  username: &twitter
facebook:
  username:
  app_id:
  publisher:
og_image: # Open Graph/Twitter 默认站点图片
social:
  type: # Person 或 Organization
  name: # 如果用户或组织名称与站点名称不同
  links: [] # 社交媒体资料链接数组

# 分析
analytics:
  provider: "false" # false, "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id:

# 文件读取设置
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 转换设置
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown 处理
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# 集合设置
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# 默认值设置 - 核心修改部分
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      classes: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      classes: wide
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      classes: wide
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      classes: wide
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      classes: wide
      author_profile: true
      share: true

# Sass/SCSS 设置
sass:
  sass_dir: _sass
  style: compressed

# 输出设置
permalink: /:categories/:title/
timezone: Etc/UTC

# 插件
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# 安全模式白名单
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# 归档设置
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML 压缩
compress_html:
  clippings: all
  ignore:
    envs: development